//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spewspeak.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21febe5be21ca2747d6649b11c697074")]
        public string WordNetDirHash {
            get {
                return ((string)(this["WordNetDirHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\inc\\WordNet\\")]
        public string WordNetRootDir {
            get {
                return ((string)(this["WordNetRootDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("93ee147c4a40fbc0a7f1e4a91fd98c18")]
        public string OpenNLPResourcesDirHash {
            get {
                return ((string)(this["OpenNLPResourcesDirHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\inc\\OpenNLPResources\\")]
        public string OpenNLPResourcesPath {
            get {
                return ((string)(this["OpenNLPResourcesPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tools\\postag\\AnnotatedSentences.txt")]
        public string POSTrainingFile {
            get {
                return ((string)(this["POSTrainingFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tools\\sentdetect\\Sentences.txt")]
        public string SentDetectTrainingFile {
            get {
                return ((string)(this["SentDetectTrainingFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string TrainingLanguage {
            get {
                return ((string)(this["TrainingLanguage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tools\\chunker\\test.txt")]
        public string ChunkerTrainingFile {
            get {
                return ((string)(this["ChunkerTrainingFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tools\\tokenize\\token.train")]
        public string TokenizerTrainingFile {
            get {
                return ((string)(this["TokenizerTrainingFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\inc\\NHunspellResources\\")]
        public string NHunspellResourcesPath {
            get {
                return ((string)(this["NHunspellResourcesPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("th_en_US_new.dat")]
        public string NHunspellEnglishThesaurus {
            get {
                return ((string)(this["NHunspellEnglishThesaurus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-pos-maxent.bin")]
        public string POSTaggerModel {
            get {
                return ((string)(this["POSTaggerModel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-chunker.bin")]
        public string ChunkerModel {
            get {
                return ((string)(this["ChunkerModel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-sent.bin")]
        public string SentDetectModel {
            get {
                return ((string)(this["SentDetectModel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-token.bin")]
        public string TokenizerModel {
            get {
                return ((string)(this["TokenizerModel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-lemmatizer.bin")]
        public string LemmatizerModel {
            get {
                return ((string)(this["LemmatizerModel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-lemmatizer.dict")]
        public string LemmatizerTrainingFile {
            get {
                return ((string)(this["LemmatizerTrainingFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5875c4996c7032a5dd027a4570548450")]
        public string NHunspellResourcesDirHash {
            get {
                return ((string)(this["NHunspellResourcesDirHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-ner-date.bin")]
        public string NameFindDateModelPath {
            get {
                return ((string)(this["NameFindDateModelPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-ner-location.bin")]
        public string NameFindLocationModelPath {
            get {
                return ((string)(this["NameFindLocationModelPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-ner-money.bin")]
        public string NameFindMoneyModelPath {
            get {
                return ((string)(this["NameFindMoneyModelPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-ner-organization.bin")]
        public string NameFindOrganizationModelPath {
            get {
                return ((string)(this["NameFindOrganizationModelPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-ner-person.bin")]
        public string NameFindPersonModelPath {
            get {
                return ((string)(this["NameFindPersonModelPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-ner-time.bin")]
        public string NameFindTimeModelPath {
            get {
                return ((string)(this["NameFindTimeModelPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("models\\en-ner-percentage.bin")]
        public string NameFindPercentageModelPath {
            get {
                return ((string)(this["NameFindPercentageModelPath"]));
            }
        }
    }
}
